In [1]:
import pandas as pd
import sqlite3
from flask import jsonify

In [2]:
DATABASE = 'catering_sqlite.db'

conn = sqlite3.connect(DATABASE)

cursor = conn.cursor()

In [3]:
cursor.execute("""CREATE TABLE IF NOT EXISTS equipment (
  `name` VARCHAR(100) NOT NULL,
  `cost_per_item` FLOAT NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`name`))""")

In [4]:
cursor.execute("""CREATE TABLE IF NOT EXISTS bar_items (
  `name` VARCHAR(50) NOT NULL,
  `cost_per_item` FLOAT NOT NULL,
  `category` VARCHAR(50) NOT NULL,
  `serving_container` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`name`),
  CONSTRAINT `fk_bar_item_container`
    FOREIGN KEY (`serving_container`)
    REFERENCES `equipment` (`name`))""")

In [5]:
cursor.execute("""CREATE TABLE IF NOT EXISTS labor_cost (
  `role` VARCHAR(45) NOT NULL,
  `cost_per_hour` FLOAT NOT NULL,
  PRIMARY KEY (`role`))""")

In [6]:
cursor.execute("""CREATE TABLE IF NOT EXISTS menu_items (
  `name` VARCHAR(100) NOT NULL,
  `course` VARCHAR(45) NOT NULL,
  `prep_time` INT NOT NULL,
  `cook_time` INT NOT NULL,
  `serving_container` VARCHAR(100) NULL DEFAULT NULL,
  `serving_utensil` VARCHAR(100) NULL DEFAULT NULL,
  `oven` TINYINT NOT NULL,
  `fridge` TINYINT NOT NULL,
  `cost_per_item` FLOAT NOT NULL,
  PRIMARY KEY (`name`),
  CONSTRAINT `fk_menu_items_container`
    FOREIGN KEY (`serving_container`)
    REFERENCES `equipment` (`name`),
  CONSTRAINT `fk_menu_items_utensil`
    FOREIGN KEY (`serving_utensil`)
    REFERENCES `equipment` (`name`))""")

In [7]:
cursor.execute("""CREATE TABLE IF NOT EXISTS `menu_item_ingredients` (
  `menu_item` VARCHAR(100) NOT NULL,
  `menu_item_ingredient` VARCHAR(250) NOT NULL,
  `quantity` FLOAT NOT NULL,
  `production_amount` INT NOT NULL,
  PRIMARY KEY (`menu_item`, `menu_item_ingredient`),
  CONSTRAINT `fk_menu_item_ingredients_menu_item`
    FOREIGN KEY (`menu_item`)
    REFERENCES `menu_items` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)""")

In [8]:
cursor.execute("""INSERT INTO equipment(name, cost_per_item, category) VALUES ('Wood Chiavari Chair', 2.97, 'Chairs'), ('Ghost Chair With Arms', 4.93, 'Chairs'), ('Industrial Metal Chair with Arms', 4.99, 'Chairs'), ('Farmhouse Cross Back Chair', 3.4, 'Chairs'), ('King Louis Chair', 7.47, 'Chairs'), ('Titan Plastic Folding Chair', 0.9, 'Chairs'), ('Titan Aluminum Plastic Folding Chair', 1.35, 'Chairs'), ('Wood Folding Chair', 1.77, 'Chairs'), ('French Bistro Folding Chair', 2.0, 'Chairs'), ("60'' Round Wood Folding Table (Seats 5-6)", 8.67, 'Tables'), ("72'' Round Wood Folding Table (Seats 8-10)", 11.47, 'Tables'), ("60'' Round Plastic Folding Table (Seats 5-6)", 9.22, 'Tables'), ("72'' Round Plastic Folding Table (Seats 8-10)", 13.62, 'Tables'), ("Plastic Folding Table - 8'x30'' banquet (Seats 8-10)", 7.5, 'Tables'), ("Plastic Folding Table - 6' x 30'' Banquet (Seats 6-8)", 4.97, 'Tables'), ("Wood Folding Table - 8'x30'' banquet (Seats 8-10)", 10.56, 'Tables'), ("Wood Folding Table - 6' x 30'' Banquet (Seats 6-8)", 6.74, 'Tables'), ("Farmhouse Folding Farm Table - 8'x40'' - Rustic - H-Legs (Seats 8-12)", 27.02, 'Tables'), ("Industrial Metal Cocktail Table 30'' Square", 15.7, 'Cocktail Tables'), ("Cocktail table - 24'' Wood Round", 12.85, 'Cocktail Tables'), ("Cocktail table - 30'' Wood Round", 13.25, 'Cocktail Tables'), ("Cocktail table - 36'' Wood Round", 13.85, 'Cocktail Tables'), ("Cocktail table - 30'' Wood Square", 12.95, 'Cocktail Tables'), ("Cocktail table - 36'' Wood Square", 13.15, 'Cocktail Tables'), ('Tablecloths (Black, White, Ivory, Navy, Grey)', 10.0, 'Table Linens'), ('Table Runners (Black, White, Ivory, Navy, Grey)', 8.0, 'Table Linens'), ('Sun Umbrella', 20.0, 'Extras'), ("Small Stage (5' x 10')", 500.0, 'Extras'), ("Large Stage (10' x 15')", 1000.0, 'Extras'), ("Small Dance Floor (12' Square)", 250.0, 'Extras'), ("Large Dance Floor (20' Square)", 500.0, 'Extras'), ('Podium', 75.0, 'Extras'), ("Plastic Dinner Plate-10''", 0.3, 'Tableware'), ("Plastic Salad/Dessert Plate- 6''", 0.15, 'Tableware'), ('Porcelain Dinner Plate-10"', 1.5, 'Tableware'), ('Porcelain Salad/Dessert Plate 6"', 1.0, 'Tableware'), ('Plastic Fork', 0.1, 'Tableware'), ('Plastic Knive', 0.1, 'Tableware'), ('Dinner Fork-Stainless (10pk)', 0.5, 'Tableware'), ('Dinner Knife-Stainless (10pk)', 0.5, 'Tableware'), ('Plastic Cups 12oz', 0.2, 'Tableware'), ('Plastic Wine Cups 9oz', 0.15, 'Tableware'), ('Beer Pilsner Glass', 1.5, 'Tableware'), ('Champagne Flute', 2.5, 'Tableware'), ('Red Wine-12oz.', 1.5, 'Tableware'), ('Water Goblets', 1.5, 'Tableware'), ('White Wine-11oz', 1.5, 'Tableware'), ('Old Fashioned Glass', 2.5, 'Tableware'), ('Oven', 400.0, 'Kitchen'), ('Refrigerator', 300.0, 'Kitchen'), ("12 '' Oval Ceramic Platter", 2.42, 'Serving'), ('18" x 5" Rectangular Ceramic Serving Platter', 4.85, 'Serving'), ('Rectangular Chafing Dish', 23.28, 'Serving'), ('Round Chafing Dish', 17.2, 'Serving'), ('Serving Spoon', 1.35, 'Serving'), ('Serving Fork', 1.35, 'Serving'), ('Spatula', 1.5, 'Serving'), ('Appetizer Tongs', 1.5, 'Serving'), ('Serving Tongs', 1.82, 'Serving'), ('Salad Serving Bowl', 3.9, 'Serving')""")

In [9]:
cursor.execute("""INSERT INTO menu_items(name, course, prep_time, cook_time, serving_container,	serving_utensil, oven, 
fridge, cost_per_item) VALUES ('Baked Chicken Wings with Thai Peanut Sauce', 'Appetizers', 40, 50, "12 '' Oval Ceramic Platter", 'Appetizer Tongs', 1, 0, 2.49), ('Homemade Chorizo Meatballs in Cilantro Masa Cups', 'Appetizers', 10, 28, "12 '' Oval Ceramic Platter", 'Appetizer Tongs', 1, 0, 0.99), ('Bruschetta Caprese', 'Appetizers', 10, 10, "12 '' Oval Ceramic Platter", 'Appetizer Tongs', 0, 1, 1.49), ('Beet-Pickled Quail Eggs', 'Appetizers', 20, 10, "12 '' Oval Ceramic Platter", 'Appetizer Tongs', 0, 1, 1.99), ('Fried Green Tomato Tacos', 'Appetizers', 20, 20, "12 '' Oval Ceramic Platter", 'Appetizer Tongs', 0, 0, 2.49), ('Chinese Sticky Rice Prawn Parcels', 'Appetizers', 20, 15, "12 '' Oval Ceramic Platter", 'Appetizer Tongs', 1, 0, 2.49), ('Ham Jalapeno Green Onion Quesadilla', 'Appetizers', 5, 10, "12 '' Oval Ceramic Platter", 'Appetizer Tongs', 1, 0, 1.99), ('Rosemary Parmesan Focaccia', 'Breads', 10, 10, '18" x 5" Rectangular Ceramic Serving Platter', 'Serving Tongs', 1, 0, 2.49), ('Buttermilk Cornbread', 'Breads', 10, 20, '18" x 5" Rectangular Ceramic Serving Platter', 'Serving Tongs', 1, 0, 2.99), ('Cheese Garlic Biscuits', 'Breads', 10, 20, '18" x 5" Rectangular Ceramic Serving Platter', 'Serving Tongs', 1, 0, 2.49), ('Basil-Buttered French Bread', 'Breads', 10, 10, '18" x 5" Rectangular Ceramic Serving Platter', 'Serving Tongs', 1, 0, 3.49), ('Tiramisu (Serves 10)', 'Desserts', 15, 3, "12 '' Oval Ceramic Platter", 'Spatula', 0, 1, 19.99), ('Triple Chocolate Cookies', 'Desserts', 15, 15, "12 '' Oval Ceramic Platter", 'Appetizer Tongs', 0, 0, 2.49), ('Sweet Cherry Pie (Serves 8)', 'Desserts', 15, 30, 'Porcelain Dinner Plate-10"', 'Spatula', 1, 0, 14.99), ('Toasted-Pecan Pie (Serves 8)', 'Desserts', 15, 30, 'Porcelain Dinner Plate-10"', 'Spatula', 1, 0, 14.99), ('Almond Biscotti', 'Desserts', 45, 15, "12 '' Oval Ceramic Platter", 'Appetizer Tongs', 0, 0, 1.99), ('French Meringues', 'Desserts', 5, 10, "12 '' Oval Ceramic Platter", 'Appetizer Tongs', 0, 0, 2.99), ('Soft Sugar Cookies', 'Desserts', 30, 20, "12 '' Oval Ceramic Platter", 'Appetizer Tongs', 0, 0, 2.49), ('Fresh Persimmon Cake (Serves 10)', 'Desserts', 10, 15, "12 '' Oval Ceramic Platter", 'Spatula', 1, 0, 24.99), ('Honey-Mustard Pork Tenderloin with Kale', 'Main Dishes', 30, 45, 'Rectangular Chafing Dish', 'Serving Tongs', 1, 0, 27.99), ('Baked Chicken Bean and Cheese Empanadas', 'Main Dishes', 30, 30, 'Rectangular Chafing Dish', 'Serving Tongs', 1, 0, 19.99), ('Ricotta and Spinach Stuffed Manicotti', 'Main Dishes', 30, 45, 'Rectangular Chafing Dish', 'Serving Spoon', 1, 0, 22.99), ('Ricotta Fettuccine Alfredo with Broccoli', 'Main Dishes', 30, 20, 'Rectangular Chafing Dish', 'Serving Tongs', 1, 1, 21.99), ('Italian Pot Roast with Artichokes and Potatoes', 'Main Dishes', 30, 60, 'Rectangular Chafing Dish', 'Serving Tongs', 1, 0, 29.99), ('Veal Ravioli with Walnut Sauce', 'Main Dishes', 30, 20, 'Rectangular Chafing Dish', 'Serving Tongs', 1, 0, 32.99), ('Teriyaki Salmon with Cucumber Salad', 'Main Dishes', 30, 20, 'Rectangular Chafing Dish', 'Spatula', 1, 1, 34.99), ('Chicken Tikka Masala', 'Main Dishes', 30, 30, 'Rectangular Chafing Dish', 'Serving Spoon', 1, 0, 23.99), ('Quiche Lorraine', 'Main Dishes', 30, 40, 'Rectangular Chafing Dish', 'Spatula', 1, 0, 21.99), ('Indian Almond Chicken with Peas', 'Main Dishes', 30, 40, 'Rectangular Chafing Dish', 'Serving Spoon', 1, 0, 26.99), ('Mexican Baked Spaghetti Squash', 'Main Dishes', 30, 35, 'Rectangular Chafing Dish', 'Serving Spoon', 1, 0, 21.99), ('Risotto With Lemon And Sun Dried Tomatoes', 'Main Dishes', 15, 40, 'Rectangular Chafing Dish', 'Serving Tongs', 1, 0, 22.99), ('Red Cabbage, Cranberry, and Apple Slaw', 'Salads', 15, 5, 'Salad Serving Bowl', 'Serving Tongs', 0, 1, 7.99), ('Quinoa Salad with Grilled Scallions, Favas and Dates', 'Salads', 15, 5, 'Salad Serving Bowl', 'Serving Spoon', 0, 1, 6.99), ('Mixed Greens with Smoked Gouda', 'Salads', 15, 5, 'Salad Serving Bowl', 'Serving Tongs', 0, 1, 7.99), ('Crunchy Romaine Toss', 'Salads', 15, 5, 'Salad Serving Bowl', 'Serving Tongs', 0, 1, 6.99), ('Panzanella', 'Salads', 15, 5, 'Salad Serving Bowl', 'Serving Spoon', 0, 1, 5.99), ('Mediterranean Chopped Salad with Tomatoes, Peppers, Feta, and Basil', 'Salads', 15, 5, 'Salad Serving Bowl', 'Serving Tongs', 0, 1, 8.99), ('Cucumber Salad', 'Salads', 15, 5, 'Salad Serving Bowl', 'Serving Spoon', 0, 1, 6.99), ('Green Beans with Roasted Tomatoes and Cumin', 'Side Dishes', 10, 20, 'Round Chafing Dish', 'Serving Tongs', 1, 0, 4.99), ('Elote, or Mexican Grilled Corn', 'Side Dishes', 5, 30, 'Round Chafing Dish', 'Serving Tongs', 1, 0, 4.99), ('Glazed Root Vegetables', 'Side Dishes', 10, 30, 'Round Chafing Dish', 'Serving Spoon', 1, 0, 3.99), ('Roasted New Potatoes', 'Side Dishes', 5, 40, 'Round Chafing Dish', 'Serving Spoon', 1, 0, 3.99), ('Best Ever Boston Baked Beans', 'Side Dishes', 10, 30, 'Round Chafing Dish', 'Serving Spoon', 1, 0, 4.99), ('Cilantro Serrano Mexican Rice', 'Side Dishes', 10, 20, 'Round Chafing Dish', 'Serving Spoon', 1, 0, 3.99), ('Grilled Fresh Artichokes', 'Side Dishes', 20, 45, 'Round Chafing Dish', 'Serving Tongs', 1, 0, 7.99), ('Pineapple Fried Rice', 'Side Dishes', 10, 20, 'Round Chafing Dish', 'Serving Spoon', 1, 0, 4.99)
""")

In [10]:
cursor.execute("""INSERT INTO bar_items (name, cost_per_item, category, serving_container) VALUES ('Coke 2L Bottle', 5.48, 'Soft Drinks', 'Plastic Cups 12oz'), ('Diet Coke 2L Bottle', 5.48, 'Soft Drinks', 'Plastic Cups 12oz'), ('Sprite 2L Bottle', 5.48, 'Soft Drinks', 'Plastic Cups 12oz'), ('Dr. Pepper 2L Bottle', 5.28, 'Soft Drinks', 'Plastic Cups 12oz'), ('Fanta 2L Bottle', 3.76, 'Soft Drinks', 'Plastic Cups 12oz'), ('Modelo 12 Pack Bottles', 32.84, 'Beer', 'Beer Pilsner Glass'), ('Budweiser 12 Pack Bottles', 26.24, 'Beer', 'Beer Pilsner Glass'), ('Bud Light 12 Pack Bottles', 26.24, 'Beer', 'Beer Pilsner Glass'), ('Heineken 12 Pack Bottles', 32.88, 'Beer', 'Beer Pilsner Glass'), ('Lagunitas 12 Pack Bottles', 33.68, 'Beer', 'Beer Pilsner Glass'), ('Sierra Nevada 12 Pack Bottles', 39.46, 'Beer', 'Beer Pilsner Glass'), ('Barefoot Chardonnay 750 mL Bottle', 11.92, 'Wine', 'White Wine-11oz'), ('Apothic Red Blend 750 mL Bottle', 18.24, 'Wine', 'Red Wine-12oz.'), ('La Crema Pinor Noir 750 mL Bottle', 45.96, 'Wine', 'Red Wine-12oz.'), ('Yellow Tail Reisling 750 mL Bottle', 19.74, 'Wine', 'White Wine-11oz'), ('Kirkland Chianti 750 mL Bottle', 17.98, 'Wine', 'Red Wine-12oz.'), ('Cupcake Pinot Grigio 750 mL Bottle', 17.66, 'Wine', 'White Wine-11oz'), ('Bollinger Champagne 750 mL Bottle', 65.8, 'Wine', 'Champagne Flute'), ("Jack Daniel's Whiskey 750 mL Bottle", 35.96, 'Liquor', 'Old Fashioned Glass'), ('Smirnoff Vodka 750 mL Bottle', 39.74, 'Liquor', 'Old Fashioned Glass'), ('Bacardi Rum 750 mL Bottle', 39.96, 'Liquor', 'Old Fashioned Glass'), ('Patron Tequila 750 mL Bottle', 70.24, 'Liquor', 'Old Fashioned Glass'), ('Tanquerey Gin 750 mL Bottle', 47.68, 'Liquor', 'Old Fashioned Glass')""")

In [11]:
cursor.execute("INSERT INTO labor_cost (role, cost_per_hour) VALUES ('Manager', 50), ('Server', 25), ('Bartender', 35), ('Event Chef', 40), ('Prep Chef', 30)")

In [12]:
menu_items_ingredients = pd.read_csv('ingredients_finished.csv').iloc[:]
menu_items_ingredients = menu_items_ingredients.drop_duplicates(subset = ['Menu_Item', 'Ingredient'])
menu_items_ingredients.columns = ['menu_item', 'menu_item_ingredient', 'quantity', 'production_amount']

In [13]:
menu_items_ingredients.to_sql('menu_item_ingredients', conn, if_exists='append', index=False)

509

In [170]:
categories = ['Beer', 'Wine', 'Liquor', 'Soft Drinks']
categorized_bar_items = {cat: [] for cat in categories}

In [171]:
bar_items = conn.execute('SELECT name, cost_per_item AS price, category FROM bar_items ORDER BY name').fetchall()

In [3]:
conn.row_factory = sqlite3.Row

In [3]:
cursor.execute("select sql from sqlite_master where type='table'")
schema = cursor.fetchall()

In [4]:
list(schema)

[('CREATE TABLE equipment (\n  `name` VARCHAR(100) NOT NULL,\n  `cost_per_item` FLOAT NOT NULL,\n  `category` VARCHAR(45) NOT NULL,\n  PRIMARY KEY (`name`))',),
 ('CREATE TABLE bar_items (\n  `name` VARCHAR(50) NOT NULL,\n  `cost_per_item` FLOAT NOT NULL,\n  `category` VARCHAR(50) NOT NULL,\n  `serving_container` VARCHAR(100) NOT NULL,\n  PRIMARY KEY (`name`),\n  CONSTRAINT `fk_bar_item_container`\n    FOREIGN KEY (`serving_container`)\n    REFERENCES `equipment` (`name`))',),
 ('CREATE TABLE labor_cost (\n  `role` VARCHAR(45) NOT NULL,\n  `cost_per_hour` FLOAT NOT NULL,\n  PRIMARY KEY (`role`))',),
 ('CREATE TABLE menu_items (\n  `name` VARCHAR(100) NOT NULL,\n  `course` VARCHAR(45) NOT NULL,\n  `prep_time` INT NOT NULL,\n  `cook_time` INT NOT NULL,\n  `serving_container` VARCHAR(100) NOT NULL,\n  `serving_utensil` VARCHAR(100) NOT NULL,\n  `oven` TINYINT NOT NULL,\n  `fridge` TINYINT NOT NULL,\n  `cost_per_item` FLOAT NOT NULL,\n  PRIMARY KEY (`name`),\n  CONSTRAINT `fk_menu_items_container`\n    FOREIGN KEY (`serving_container`)\n    REFERENCES `equipment` (`name`),\n  CONSTRAINT `fk_menu_items_utensil`\n    FOREIGN KEY (`serving_utensil`)\n    REFERENCES `equipment` (`name`))',),
 ('CREATE TABLE `menu_item_ingredients` (\n  `menu_item` VARCHAR(100) NOT NULL,\n  `menu_item_ingredient` VARCHAR(250) NOT NULL,\n  `quantity` FLOAT NOT NULL,\n  `production_amount` INT NOT NULL,\n  PRIMARY KEY (`menu_item`, `menu_item_ingredient`),\n  CONSTRAINT `fk_menu_item_ingredients_menu_item`\n    FOREIGN KEY (`menu_item`)\n    REFERENCES `menu_items` (`name`)\n    ON DELETE CASCADE\n    ON UPDATE CASCADE)',)]

In [135]:
for table in tables:
    print(table['name'])

equipment
bar_items
labor_cost
menu_items
menu_item_ingredients

In [43]:
bar_items = conn.execute("SELECT name FROM bar_items").fetchall()

In [49]:
[{'name':x['name']} for x in bar_items]

[{'name': 'Apothic Red Blend 750 mL Bottle'},
 {'name': 'Bacardi Rum 750 mL Bottle'},
 {'name': 'Barefoot Chardonnay 750 mL Bottle'},
 {'name': 'Bollinger Champagne 750 mL Bottle'},
 {'name': 'Bud Light 12 Pack Bottles'},
 {'name': 'Budweiser 12 Pack Bottles'},
 {'name': 'Coke 2L Bottle'},
 {'name': 'Cupcake Pinot Grigio 750 mL Bottle'},
 {'name': 'Diet Coke 2L Bottle'},
 {'name': 'Dr. Pepper 2L Bottle'},
 {'name': 'Fanta 2L Bottle'},
 {'name': 'Heineken 12 Pack Bottles'},
 {'name': "Jack Daniel's Whiskey 750 mL Bottle"},
 {'name': 'Kirkland Chianti 750 mL Bottle'},
 {'name': 'La Crema Pinor Noir 750 mL Bottle'},
 {'name': 'Lagunitas 12 Pack Bottles'},
 {'name': 'Modelo 12 Pack Bottles'},
 {'name': 'Patron Tequila 750 mL Bottle'},
 {'name': 'Sierra Nevada 12 Pack Bottles'},
 {'name': 'Smirnoff Vodka 750 mL Bottle'},
 {'name': 'Sprite 2L Bottle'},
 {'name': 'Tanquerey Gin 750 mL Bottle'},
 {'name': 'Yellow Tail Reisling 750 mL Bottle'}]

In [42]:
bar_items.fetchall()

AttributeError: 'list' object has no attribute 'fetchall'

In [216]:
categorized_bar_items = {cat: [] for cat in categories}
for item in bar_items:
    for cat in categories:
        if cat == item['category']:
            categorized_bar_items[cat].append(dict(item))

In [208]:
count = conn.execute(f"SELECT COUNT(*) FROM bar_items").fetchall

In [214]:
count[0][count[0].keys()[0]]

23

In [235]:
[(x,y) for (x,y) in (categorized_bar_items.keys(), categorized_bar_items.values())]

ValueError: too many values to unpack (expected 2)

In [238]:
from flask import jsonify

In [239]:
item_types = ['menu', 'bar', 'equipment']

In [242]:
mapper = {'menu':'menu_items', 'bar':'bar_items', 'equipment':'equipment'}

In [5]:
conn.row_factory = sqlite3.Row

In [275]:
cursor = conn.cursor()
pd.DataFrame(cursor.execute("SELECT * FROM menu_item_ingredients LIMIT 10").fetchall(), columns = [x[0] for x in cursor.description]).columns

Index(['menu_item', 'menu_item_ingredient', 'quantity', 'production_amount'], dtype='object')

In [260]:
cursor.description

(('name', None, None, None, None, None, None),
 ('course', None, None, None, None, None, None),
 ('prep_time', None, None, None, None, None, None),
 ('cook_time', None, None, None, None, None, None),
 ('serving_container', None, None, None, None, None, None),
 ('serving_utensil', None, None, None, None, None, None),
 ('oven', None, None, None, None, None, None),
 ('fridge', None, None, None, None, None, None),
 ('cost_per_item', None, None, None, None, None, None))

In [261]:
oven, fridge = (False, False)

In [266]:
my_string = 'hey'

In [267]:
if True and my_string == 'hey':
    print('True')

True

In [269]:
my_dict = {'other_details': {'eventDate': '5555-05-05', 'eventStartTime': '05:55', 'eventEndTime': '05:55', 'numGuests': '50', 'eventType': 'wedding', 'eventLocation': '12 Rue Bichat Lyon France', 'venueKitchen': 'no', 'specialRequests': '', 'barService': 'yes', 'equipmentRental': 'yes'}}

In [270]:
my_dict.get('other_details')

{'eventDate': '5555-05-05',
 'eventStartTime': '05:55',
 'eventEndTime': '05:55',
 'numGuests': '50',
 'eventType': 'wedding',
 'eventLocation': '12 Rue Bichat Lyon France',
 'venueKitchen': 'no',
 'specialRequests': '',
 'barService': 'yes',
 'equipmentRental': 'yes'}

In [9]:
conn = sqlite3.connect(DATABASE)
cursor = conn.cursor()
conn.row_factory = sqlite3.Row

In [428]:
item_name = 'Baked Chicken Wings with Thai Peanut Sauce'

In [429]:
menu_item_details =  conn.execute(f'''SELECT * FROM menu_items WHERE name = "{item_name}"''').fetchone()
ingredient_details = conn.execute(f'''SELECT * FROM menu_items 
                                LEFT JOIN menu_item_ingredients AS mii ON menu_items.name = mii.menu_item 
                                WHERE menu_items.name = "{item_name}"''').fetchall()

In [23]:
info = conn.execute("SELECT * FROM menu_items AS m LEFT JOIN equipment AS e on m.serving_container = e.name").fetchall()

In [24]:
pd.DataFrame(info)

,0,1,2,3,4,5,6,7,8,9,10,11
0,Baked Chicken Wings with Thai Peanut Sauce,Appetizers,40,50,,Appetizer Tongs,1,0,2.49,None,NaN,None
1,Homemade Chorizo Meatballs in Cilantro Masa Cups,Appetizers,10,28,12 '' Oval Ceramic Platter,Appetizer Tongs,1,0,0.99,12 '' Oval Ceramic Platter,2.42,Serving
2,Bruschetta Caprese,Appetizers,10,10,12 '' Oval Ceramic Platter,Appetizer Tongs,0,1,1.49,12 '' Oval Ceramic Platter,2.42,Serving
3,Beet-Pickled Quail Eggs,Appetizers,20,10,12 '' Oval Ceramic Platter,Appetizer Tongs,0,1,1.99,12 '' Oval Ceramic Platter,2.42,Serving
4,Fried Green Tomato Tacos,Appetizers,20,20,12 '' Oval Ceramic Platter,Appetizer Tongs,0,0,2.49,12 '' Oval Ceramic Platter,2.42,Serving
5,Chinese Sticky Rice Prawn Parcels,Appetizers,20,15,12 '' Oval Ceramic Platter,Appetizer Tongs,1,0,2.49,12 '' Oval Ceramic Platter,2.42,Serving
6,Ham Jalapeno Green Onion Quesadilla,Appetizers,5,10,12 '' Oval Ceramic Platter,Appetizer Tongs,1,0,1.99,12 '' Oval Ceramic Platter,2.42,Serving
7,Rosemary Parmesan Focaccia,Breads,10,10,"18"" x 5"" Rectangular Ceramic Serving Platter",Serving Tongs,1,0,2.49,"18"" x 5"" Rectangular Ceramic Serving Platter",4.85,Serving
8,Buttermilk Cornbread,Breads,10,20,"18"" x 5"" Rectangular Ceramic Serving Platter",Serving Tongs,1,0,2.99,"18"" x 5"" Rectangular Ceramic Serving Platter",4.85,Serving
9,Cheese Garlic Biscuits,Breads,10,20,"18"" x 5"" Rectangular Ceramic Serving Platter",Serving Tongs,1,0,2.49,"18"" x 5"" Rectangular Ceramic Serving Platter",4.85,Serving
10,Basil-Buttered French Bread,Breads,10,10,"18"" x 5"" Rectangular Ceramic Serving Platter",Serving Tongs,1,0,3.49,"18"" x 5"" Rectangular Ceramic Serving Platter",4.85,Serving
11,Tiramisu (Serves 10),Desserts,15,3,12 '' Oval Ceramic Platter,Spatula,0,1,19.99,12 '' Oval Ceramic Platter,2.42,Serving
12,Triple Chocolate Cookies,Desserts,15,15,12 '' Oval Ceramic Platter,Appetizer Tongs,0,0,2.49,12 '' Oval Ceramic Platter,2.42,Serving
13,Sweet Cherry Pie (Serves 8),Desserts,15,30,"Porcelain Dinner Plate-10""",Spatula,1,0,14.99,"Porcelain Dinner Plate-10""",1.50,Tableware
14,Toasted-Pecan Pie (Serves 8),Desserts,15,30,"Porcelain Dinner Plate-10""",Spatula,1,0,14.99,"Porcelain Dinner Plate-10""",1.50,Tableware
15,Almond Biscotti,Desserts,45,15,12 '' Oval Ceramic Platter,Appetizer Tongs,0,0,1.99,12 '' Oval Ceramic Platter,2.42,Serving
16,French Meringues,Desserts,5,10,12 '' Oval Ceramic Platter,Appetizer Tongs,0,0,2.99,12 '' Oval Ceramic Platter,2.42,Serving
17,Soft Sugar Cookies,Desserts,30,20,12 '' Oval Ceramic Platter,Appetizer Tongs,0,0,2.49,12 '' Oval Ceramic Platter,2.42,Serving
18,Fresh Persimmon Cake (Serves 10),Desserts,10,15,12 '' Oval Ceramic Platter,Spatula,1,0,24.99,12 '' Oval Ceramic Platter,2.42,Serving
19,Honey-Mustard Pork Tenderloin with Kale,Main Dishes,30,45,Rectangular Chafing Dish,Serving Tongs,1,0,27.99,Rectangular Chafing Dish,23.28,Serving
20,Baked Chicken Bean and Cheese Empanadas,Main Dishes,30,30,Rectangular Chafing Dish,Serving Tongs,1,0,19.99,Rectangular Chafing Dish,23.28,Serving
21,Ricotta and Spinach Stuffed Manicotti,Main Dishes,30,45,Rectangular Chafing Dish,Serving Spoon,1,0,22.99,Rectangular Chafing Dish,23.28,Serving
22,Ricotta Fettuccine Alfredo with Broccoli,Main Dishes,30,20,Rectangular Chafing Dish,Serving Tongs,1,1,21.99,Rectangular Chafing Dish,23.28,Serving
23,Italian Pot Roast with Artichokes and Potatoes,Main Dishes,30,60,Rectangular Chafing Dish,Serving Tongs,1,0,29.99,Rectangular Chafing Dish,23.28,Serving
24,Veal Ravioli with Walnut Sauce,Main Dishes,30,20,Rectangular Chafing Dish,Serving Tongs,1,0,32.99,Rectangular Chafing Dish,23.28,Serving
25,Teriyaki Salmon with Cucumber Salad,Main Dishes,30,20,Rectangular Chafing Dish,Spatula,1,1,34.99,Rectangular Chafing Dish,23.28,Serving
26,Chicken Tikka Masala,Main Dishes,30,30,Rectangular Chafing Dish,Serving Spoon,1,0,23.99,Rectangular Chafing Dish,23.28,Serving
27,Quiche Lorraine,Main Dishes,30,40,Rectangular Chafing Dish,Spatula,1,0,21.99,Rectangular Chafing Dish,23.28,Serving
28,Indian Almond Chicken with Peas,Main Dishes,30,40,Rectangular Chafing Dish,Serving Spoon,1,0,26.99,Rectangular Chafing Dish,23.28,Serving
29,Mexican Baked Spaghetti Squash,Main Dishes,30,35,Rectangular Chafing Dish,Serving Spoon,1,0,21.99,Rectangular Chafing Dish,23.28,Serving
30,Risotto With Lemon And Sun Dried Tomatoes,Main Dishes,15,40,Rectangular Chafing Dish,Serving Tongs,1,0,22.99,Rectangular Chafing Dish,23.28,Serving
31,"Red Cabbage, Cranberry, and Apple Slaw",Salads,15,5,Salad Serving Bowl,Serving Tongs,0,1,7.99,Salad Serving Bowl,3.90,Serving
32,"Quinoa Salad with Grilled Scallions, Favas and...",Salads,15,5,Salad Serving Bowl,Serving Spoon,0,1,6.99,Salad Serving Bowl,3.90,Serving
33,Mixed Greens with Smoked Gouda,Salads,15,5,Salad Serving Bowl,Serving Tongs,0,1,7.99,Salad Serving Bowl,3.90,Serving
34,Crunchy Romaine Toss,Salads,15,5,Salad Serving Bowl,Serving Tongs,0,1,6.99,Salad Serving Bowl,3.90,Serving
35,Panzanella,Salads,15,5,Salad Serving Bowl,Serving Spoon,0,1,5.99,Salad Serving Bowl,3.90,Serving
36,"Mediterranean Chopped Salad with Tomatoes, Pep...",Salads,15,5,Salad Serving Bowl,Serving Tongs,0,1,8.99,Salad Serving Bowl,3.90,Serving
37,Cucumber Salad,Salads,15,5,Salad Serving Bowl,Serving Spoon,0,1,6.99,Salad Serving Bowl,3.90,Serving
38,Green Beans with Roasted Tomatoes and Cumin,Side Dishes,10,20,Round Chafing Dish,Serving Tongs,1,0,4.99,Round Chafing Dish,17.20,Serving
39,"Elote, or Mexican Grilled Corn",Side Dishes,5,30,Round Chafing Dish,Serving Tongs,1,0,4.99,Round Chafing Dish,17.20,Serving
40,Glazed Root Vegetables,Side Dishes,10,30,Round Chafing Dish,Serving Spoon,1,0,3.99,Round Chafing Dish,17.20,Serving
41,Roasted New Potatoes,Side Dishes,5,40,Round Chafing Dish,Serving Spoon,1,0,3.99,Round Chafing Dish,17.20,Serving
42,Best Ever Boston Baked Beans,Side Dishes,10,30,Round Chafing Dish,Serving Spoon,1,0,4.99,Round Chafing Dish,17.20,Serving
43,Cilantro Serrano Mexican Rice,Side Dishes,10,20,Round Chafing Dish,Serving Spoon,1,0,3.99,Round Chafing Dish,17.20,Serving
44,Grilled Fresh Artichokes,Side Dishes,20,45,Round Chafing Dish,Serving Tongs,1,0,7.99,Round Chafing Dish,17.20,Serving
45,Pineapple Fried Rice,Side Dishes,10,20,Round Chafing Dish,Serving Spoon,1,0,4.99,Round Chafing Dish,17.20,Serving

In [431]:
menu_items_list_json= list(zip(menu_item_details.keys(), list(menu_item_details)))

In [432]:
menu_items_list_json

[('name', 'Baked Chicken Wings with Thai Peanut Sauce'),
 ('course', 'Appetizers'),
 ('prep_time', 40),
 ('cook_time', 50),
 ('serving_container', "12 '' Oval Ceramic Platter"),
 ('serving_utensil', 'Appetizer Tongs'),
 ('oven', 1),
 ('fridge', 0),
 ('cost_per_item', 2.49)]

In [418]:
pd.DataFrame(ingredient_details)

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,Baked Chicken Wings with Thai Peanut Sauce,Appetizers,40,50,12 '' Oval Ceramic Platter,Appetizer Tongs,1,0,2.49,Baked Chicken Wings with Thai Peanut Sauce,"cloves garlic, peeled and roughly chopped",2.0,40
1,Baked Chicken Wings with Thai Peanut Sauce,Appetizers,40,50,12 '' Oval Ceramic Platter,Appetizer Tongs,1,0,2.49,Baked Chicken Wings with Thai Peanut Sauce,cooking spray,0.0,40
2,Baked Chicken Wings with Thai Peanut Sauce,Appetizers,40,50,12 '' Oval Ceramic Platter,Appetizer Tongs,1,0,2.49,Baked Chicken Wings with Thai Peanut Sauce,cup coconut milk,1.0,40
3,Baked Chicken Wings with Thai Peanut Sauce,Appetizers,40,50,12 '' Oval Ceramic Platter,Appetizer Tongs,1,0,2.49,Baked Chicken Wings with Thai Peanut Sauce,cup smooth peanut butter,0.5,40
4,Baked Chicken Wings with Thai Peanut Sauce,Appetizers,40,50,12 '' Oval Ceramic Platter,Appetizer Tongs,1,0,2.49,Baked Chicken Wings with Thai Peanut Sauce,"inch knob ginger, peeled and roughly chopped (...",1.0,40
5,Baked Chicken Wings with Thai Peanut Sauce,Appetizers,40,50,12 '' Oval Ceramic Platter,Appetizer Tongs,1,0,2.49,Baked Chicken Wings with Thai Peanut Sauce,"lime wedges, chopped green onion, chopped cila...",0.0,40
6,Baked Chicken Wings with Thai Peanut Sauce,Appetizers,40,50,12 '' Oval Ceramic Platter,Appetizer Tongs,1,0,2.49,Baked Chicken Wings with Thai Peanut Sauce,"lime, juiced",0.5,40
7,Baked Chicken Wings with Thai Peanut Sauce,Appetizers,40,50,12 '' Oval Ceramic Platter,Appetizer Tongs,1,0,2.49,Baked Chicken Wings with Thai Peanut Sauce,"pounds chicken wings, skinned with tips remove...",5.0,40
8,Baked Chicken Wings with Thai Peanut Sauce,Appetizers,40,50,12 '' Oval Ceramic Platter,Appetizer Tongs,1,0,2.49,Baked Chicken Wings with Thai Peanut Sauce,tablespoons brown sugar,2.0,40
9,Baked Chicken Wings with Thai Peanut Sauce,Appetizers,40,50,12 '' Oval Ceramic Platter,Appetizer Tongs,1,0,2.49,Baked Chicken Wings with Thai Peanut Sauce,tablespoons fish sauce,2.0,40
10,Baked Chicken Wings with Thai Peanut Sauce,Appetizers,40,50,12 '' Oval Ceramic Platter,Appetizer Tongs,1,0,2.49,Baked Chicken Wings with Thai Peanut Sauce,teaspoon red pepper flakes,0.5,40
11,Baked Chicken Wings with Thai Peanut Sauce,Appetizers,40,50,12 '' Oval Ceramic Platter,Appetizer Tongs,1,0,2.49,Baked Chicken Wings with Thai Peanut Sauce,teaspoon sesame oil,1.0,40

In [417]:
ingredient_details[0].keys()

['name',
 'course',
 'prep_time',
 'cook_time',
 'serving_container',
 'serving_utensil',
 'oven',
 'fridge',
 'cost_per_item',
 'menu_item',
 'menu_item_ingredient',
 'quantity',
 'production_amount']

In [260]:
production = ('production_amount', ingredient_details[0]['production_amount'])

In [263]:
items_quantities = sum([list(x)[1::-1] for x in ingredient_details], [])
labels = ingredient_details[0].keys()[1::-1] * len(ingredient_details)
labels = [labels[x] + '_' + str(x//2 + 1) for x in range(len(labels))]
production = [('production_amount', ingredient_details[0]['production_amount'])]
ingredients_list_json = production + list(zip(labels, items_quantities))

In [264]:
ingredients_list_json

[('production_amount', 5),
 ('quantity_1', 1.0),
 ('menu_item_ingredient_1',
  '(10 ounce) package frozen chopped spinach, thawed and squeezed dry'),
 ('quantity_2', 1.0),
 ('menu_item_ingredient_2', '(15 ounce) container ricotta cheese'),
 ('quantity_3', 1.0),
 ('menu_item_ingredient_3', '(8 ounce) package manicotti shells'),
 ('quantity_4', 1.0),
 ('menu_item_ingredient_4', '1/2 cups shredded mozzarella cheese, divided'),
 ('quantity_5', 0.5),
 ('menu_item_ingredient_5', 'cup grated Parmesan cheese, divided'),
 ('quantity_6', 0.5),
 ('menu_item_ingredient_6', 'cup minced onion'),
 ('quantity_7', 6.0),
 ('menu_item_ingredient_7', 'cups ClassicoÃ‚Â® Tomato and Basil Sauce'),
 ('quantity_8', 1.5),
 ('menu_item_ingredient_8', 'cups water'),
 ('quantity_9', 1.0),
 ('menu_item_ingredient_9', 'egg'),
 ('quantity_10', 0.25),
 ('menu_item_ingredient_10', 'teaspoon garlic powder'),
 ('quantity_11', 0.5),
 ('menu_item_ingredient_11', 'teaspoon pepper'),
 ('quantity_12', 2.0),
 ('menu_item_ingredient_12', 'teaspoons minced fresh parsley')]

In [200]:
full_list_json = menu_items_list_json + ingredients_list_json
dict(full_list_json)

{'name': 'Beet-Pickled Quail Eggs',
 'course': 'Appetizers',
 'prep_time': 20,
 'cook_time': 10,
 'serving_container': "12 '' Oval Ceramic Platter",
 'serving_utensil': 'Appetizer Tongs',
 'oven': 0,
 'fridge': 1,
 'cost_per_item': 1.99,
 'menu_item_ingredient_1': 0.0,
 'quantity_1': 'Hot sauce, celery leaves, and flaky sea salt, for serving',
 'menu_item_ingredient_2': 0.5,
 'quantity_2': 'cup sugar',
 'menu_item_ingredient_3': 1.0,
 'quantity_3': 'cup white balsamic vinegar',
 'menu_item_ingredient_4': 1.0,
 'quantity_4': 'dried bay leaf',
 'menu_item_ingredient_5': 24.0,
 'quantity_5': 'quail eggs (available at dartagnan.com)',
 'menu_item_ingredient_6': 1.0,
 'quantity_6': 'small red beet, peeled and coarsely grated',
 'menu_item_ingredient_7': 1.0,
 'quantity_7': 'teaspoon coarse salt',
 'menu_item_ingredient_8': 1.0,
 'quantity_8': 'teaspoon juniper berries'}

In [184]:
items_quantities = sum([list(x)[2:0] for x in ingredient_details], [])

In [189]:
[list(x)[2:0:-1] for x in ingredient_details]

[[8, 0.0],
 [8, 0.5],
 [8, 1.0],
 [8, 1.0],
 [8, 24.0],
 [8, 1.0],
 [8, 1.0],
 [8, 1.0]]

In [203]:
mydict = {'name': 'Budweiser 12 Pack Bottles', 'cost_per_item': 26.24, 'category': 'Beer', 'serving_container': 'Beer Pilsner Glass'}

In [222]:
for x in mydict.items():
    print(x[0] + ' = "' + str(x[1]) + '"')

name = "Budweiser 12 Pack Bottles"
cost_per_item = "26.24"
category = "Beer"
serving_container = "Beer Pilsner Glass"

In [227]:
valueslist = [x[0] + ' = "' + str(x[1]) + '"' if type(x[1]) == str else x[0] + ' = ' + str(x[1]) for x in mydict.items()]

In [228]:
', '.join(valueslist)

'name = "Budweiser 12 Pack Bottles", cost_per_item = 26.24, category = "Beer", serving_container = "Beer Pilsner Glass"'

In [230]:
pd.DataFrame(conn.execute("UPDATE bar_items SET ").fetchall())

,0,1,2,3
0,Coke 2L Bottle,5.48,Soft Drinks,Plastic Cups 12oz
1,Diet Coke 2L Bottle,5.48,Soft Drinks,Plastic Cups 12oz
2,Sprite 2L Bottle,5.48,Soft Drinks,Plastic Cups 12oz
3,Dr. Pepper 2L Bottle,5.28,Soft Drinks,Plastic Cups 12oz
4,Fanta 2L Bottle,3.76,Soft Drinks,Plastic Cups 12oz
5,Modelo 12 Pack Bottles,32.84,Beer,Beer Pilsner Glass
6,Budweiser 12 Pack Bottles,26.24,Beer,Beer Pilsner Glass
7,Bud Light 12 Pack Bottles,26.24,Beer,Beer Pilsner Glass
8,Heineken 12 Pack Bottles,32.88,Beer,Beer Pilsner Glass
9,Lagunitas 12 Pack Bottles,33.68,Beer,Beer Pilsner Glass
10,Sierra Nevada 12 Pack Bottles,39.46,Beer,Beer Pilsner Glass
11,Barefoot Chardonnay 750 mL Bottle,11.92,Wine,White Wine-11oz
12,Apothic Red Blend 750 mL Bottle,18.24,Wine,Red Wine-12oz.
13,La Crema Pinor Noir 750 mL Bottle,45.96,Wine,Red Wine-12oz.
14,Yellow Tail Reisling 750 mL Bottle,19.74,Wine,White Wine-11oz
15,Kirkland Chianti 750 mL Bottle,17.98,Wine,Red Wine-12oz.
16,Cupcake Pinot Grigio 750 mL Bottle,17.66,Wine,White Wine-11oz
17,Bollinger Champagne 750 mL Bottle,65.80,Wine,Champagne Flute
18,Jack Daniel's Whiskey 750 mL Bottle,35.96,Liquor,Old Fashioned Glass
19,Smirnoff Vodka 750 mL Bottle,39.74,Liquor,Old Fashioned Glass
20,Bacardi Rum 750 mL Bottle,39.96,Liquor,Old Fashioned Glass
21,Patron Tequila 750 mL Bottle,70.24,Liquor,Old Fashioned Glass
22,Tanquerey Gin 750 mL Bottle,47.68,Liquor,Old Fashioned Glass

In [393]:
conn.close()

In [425]:
mydict = {'name': 'Grilled Fresh Artichokes', 'course': 'Side Dishes', 'prep_time': '20', 'cook_time': '45', 'serving_container': 'Round Chafing Dish', 'serving_utensil': 'Serving Tongs', 'oven': '1', 'fridge': '0', 'cost_per_item': '7.99', 'production_amount': '10', 'quantity_1': '4', 'menu_item_ingredient_1': 'fresh artichokes (about 3/4 lb. each)', 'quantity_2': '5', 'menu_item_ingredient_2': 'fresh parsley sprigs', 'quantity_3': '3', 'menu_item_ingredient_3': 'garlic cloves', 'quantity_4': '0', 'menu_item_ingredient_4': 'garnish: fresh flat-leaf parsley sprigs', 'quantity_5': '1', 'menu_item_ingredient_5': 'lemon, thinly sliced', 'quantity_6': '0', 'menu_item_ingredient_6': 'salt and pepper', 'quantity_7': '3', 'menu_item_ingredient_7': 'tablespoons olive oil', 'quantity_8': '2', 'menu_item_ingredient_8': 'teaspoons salt'}

In [426]:
mydict

{'name': 'Grilled Fresh Artichokes',
 'course': 'Side Dishes',
 'prep_time': '20',
 'cook_time': '45',
 'serving_container': 'Round Chafing Dish',
 'serving_utensil': 'Serving Tongs',
 'oven': '1',
 'fridge': '0',
 'cost_per_item': '7.99',
 'production_amount': '10',
 'quantity_1': '4',
 'menu_item_ingredient_1': 'fresh artichokes (about 3/4 lb. each)',
 'quantity_2': '5',
 'menu_item_ingredient_2': 'fresh parsley sprigs',
 'quantity_3': '3',
 'menu_item_ingredient_3': 'garlic cloves',
 'quantity_4': '0',
 'menu_item_ingredient_4': 'garnish: fresh flat-leaf parsley sprigs',
 'quantity_5': '1',
 'menu_item_ingredient_5': 'lemon, thinly sliced',
 'quantity_6': '0',
 'menu_item_ingredient_6': 'salt and pepper',
 'quantity_7': '3',
 'menu_item_ingredient_7': 'tablespoons olive oil',
 'quantity_8': '2',
 'menu_item_ingredient_8': 'teaspoons salt'}

In [288]:
menu_items_updates = [updates[0] + ' = "' + str(updates[1]) + '"' for updates in list(mydict.items())[0:9]]

In [289]:
menu_items_values_clause = ', '.join(menu_items_updates)

In [290]:
menu_items_values_clause

'name = "Grilled Fresh Artichokes", course = "Side Dishes", prep_time = "20", cook_time = "45", serving_container = "Round Chafing Dish", serving_utensil = "Serving Tongs", oven = "1", fridge = "0", cost_per_item = "7.99"'

In [421]:
quantities = ['"' + str(update[1]) + '"' for update in list(mydict.items())[10::2]]
ingredients = ['"' + str(update[1]) + '"' for update in list(mydict.items())[11::2]]
production = ['"' + mydict['production_amount'] + '"' for x in range(len(quantities))]
menu_item = [mydict['name'] for x in range(len(quantities))]

In [422]:
menu_item

['Grilled Fresh Artichokes',
 'Grilled Fresh Artichokes',
 'Grilled Fresh Artichokes',
 'Grilled Fresh Artichokes',
 'Grilled Fresh Artichokes',
 'Grilled Fresh Artichokes',
 'Grilled Fresh Artichokes',
 'Grilled Fresh Artichokes']

In [423]:
update_query = 'INSERT INTO menu_item_ingredients (menu_item, quantity, menu_item_ingredien, production_amount) VALUES '  + ''.join(["(" + menu_item[x] + ', ' + quantities[x] + ', ' + ingredients[x] + ', ' + production[x] + ")," for x in range(len(quantities))])[:-1]

In [424]:
update_query

'INSERT INTO menu_item_ingredients (menu_item, quantity, menu_item_ingredien, production_amount) VALUES (Grilled Fresh Artichokes, "4", "fresh artichokes (about 3/4 lb. each)", "10"),(Grilled Fresh Artichokes, "5", "fresh parsley sprigs", "10"),(Grilled Fresh Artichokes, "3", "garlic cloves", "10"),(Grilled Fresh Artichokes, "0", "garnish: fresh flat-leaf parsley sprigs", "10"),(Grilled Fresh Artichokes, "1", "lemon, thinly sliced", "10"),(Grilled Fresh Artichokes, "0", "salt and pepper", "10"),(Grilled Fresh Artichokes, "3", "tablespoons olive oil", "10"),(Grilled Fresh Artichokes, "2", "teaspoons salt", "10")'

In [373]:
delete_query = f'DELETE FROM menu_item_ingredients WHERE menu_item = {mydict['name']}'

In [374]:
delete_query

'DELETE FROM menu_item_ingredients WHERE menu_item = Grilled Fresh Artichokes'

In [436]:
row = conn.execute("SELECT * FROM menu_items LEFT JOIN menu_item_ingredients ON menu_items.name = menu_item_ingredients.menu_item").fetchall()

In [441]:
dict(zip(row.keys(), ['' for c in range(len(row.keys()))]))

{'name': '',
 'course': '',
 'prep_time': '',
 'cook_time': '',
 'serving_container': '',
 'serving_utensil': '',
 'oven': '',
 'fridge': '',
 'cost_per_item': '',
 'menu_item': '',
 'menu_item_ingredient': '',
 'quantity': '',
 'production_amount': ''}

In [453]:
my_string = ['string', 'another_string']

In [454]:
second_string = my_string.copy()

In [456]:
second_string[0] = 'blah'

In [460]:
for (x, y) in enumerate(my_string):
    print(x,y)

0 string
1 another_string

In [451]:
my_string[:0] + ['third_string'] + my_string[0:]

['third_string', 'string', 'another_string']

In [452]:
my_string.pop(1)

'another_string'

In [466]:
ingredients = ['"Salt and freshly ground pepper, to taste"', '"Tbs. finely chopped fresh rosemary or 1 1Ã¢Â\x81â€ž2 tsp. dried"', '"cup extra-virgin olive oil-"', '"garlic cloves, minced"', '"lb. small to medium new potatoes, scrubbed"']

In [467]:
for (x, ingredient) in enumerate(ingredients.copy()):
    if ingredient[-2:] == '+"':
        ingredients = ingredients[:x+1] + ['"New ingredient"',] + ingredients[x+1:]
        quantities = quantities[:x+1] + ['0'] + quantities[x+1:]
        production = production + production[:1]
        menu_item = menu_item + menu_item[:1]
    elif ingredient[-2:] == '-"':
        ingredients = ingredient[:x] + ingredients[1+x:]
        quantities = quantities[:x] + quantities[1+x:]
        production = production[:-1]
        menu_item = menu_item[:-1]
    else:
        pass

TypeError: can only concatenate str (not "list") to str

In [468]:
ingredients = conn.execute("SELECT * FROM menu_item_ingredients").fetchall()

In [469]:
pd.DataFrame(ingredients)

,0,1,2,3
0,Bruschetta Caprese,to 12 Italian bread slices (depends on the siz...,6.0,6
1,Bruschetta Caprese,cup Extra Virgin Olive Oli,1.0,6
2,Bruschetta Caprese,tablespoon dry oregano,1.0,6
3,Bruschetta Caprese,salt,0.0,6
4,Bruschetta Caprese,garlic clove,1.0,6
...,...,...,...,...
506,Baked Chicken Wings with Thai Peanut Sauce,"lime, juiced",0.5,40
507,Baked Chicken Wings with Thai Peanut Sauce,"pounds chicken wings, skinned with tips remove...",6.0,40
508,Baked Chicken Wings with Thai Peanut Sauce,tablespoons brown sugar,2.0,40
509,Baked Chicken Wings with Thai Peanut Sauce,tablespoons fish sauce,2.0,40
510,Baked Chicken Wings with Thai Peanut Sauce,teaspoon red pepper flakes,0.5,40